#!/usr/bin/env python3
import json, subprocess, sys, time
from pathlib import Path

HOME = Path.home()
URL = "http://127.0.0.1:8080/completion"

def say(msg):
    print(f"[yolo-new-site] {msg}", flush=True)

def rule(title=""):
    bar = "=" * 56
    print(f"\n{bar}\n{title}\n{bar}", flush=True)

def ensure_server():
    chk = subprocess.run(["pgrep", "-f", "llama-server"], capture_output=True, text=True)
    if chk.returncode == 0:
        say("llama-server already running")
        return
    say("starting llama-server...")
    subprocess.Popen(
        [
            str(HOME / "llama.cpp" / "build" / "bin" / "llama-server"),
            "-hf", "Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF:Q4_K_M",
            "--host", "127.0.0.1",
            "--port", "8080",
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    time.sleep(5)
    say("llama-server started")

def clean_html(text):
    text = text.replace("```html", "").replace("```", "")
    lower = text.lower()
    i = lower.find("<!doctype html>")
    if i != -1:
        text = text[i:]
    if "</html>" not in text.lower():
        text += "\n</html>"
    j = text.lower().find("</html>")
    if j != -1:
        text = text[:j+7]
    return text.strip() + "\n"

def main():
    if len(sys.argv) < 3:
        print('Usage: yolo-new-site "repo-name" "prompt"')
        sys.exit(1)

    name = sys.argv[1]
    prompt = sys.argv[2]

    ensure_server()

    repo_dir = HOME / name
    if repo_dir.exists():
        print(f"Directory already exists: {repo_dir}")
        sys.exit(2)

    say(f"creating repo dir: {repo_dir}")
    repo_dir.mkdir(parents=True, exist_ok=False)

    full_prompt = f"""Return ONLY valid complete HTML.
Do not use markdown fences.
Start with <!DOCTYPE html>.
End with </html>.
Use inline CSS only.
Use a dark modern design.
Do not invent broken internal links.

Site name: {name}
Topic: {prompt}
"""

    payload = {
        "prompt": full_prompt,
        "n_predict": 1400,
        "temperature": 0.2,
        "stop": ["</html>"],
        "stream": True,
    }

    rule("MODEL OUTPUT")
    proc = subprocess.Popen(
        ["curl", "-N", "-s", URL, "-H", "Content-Type: application/json", "-d", json.dumps(payload)],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        bufsize=1,
    )

    parts = []
    for line in proc.stdout:
        if not line.startswith("data: "):
            continue
        chunk = line[6:].strip()
        if not chunk or chunk == "[DONE]":
            continue
        try:
            data = json.loads(chunk)
        except json.JSONDecodeError:
            continue
        text = data.get("content", "")
        if text:
            print(text, end="", flush=True)
            parts.append(text)

    proc.wait()
    print()
    rule("POST-PROCESS")

    out = clean_html("".join(parts))
    (repo_dir / "index.html").write_text(out, encoding="utf-8")
    (repo_dir / "README.md").write_text(f"# {name}\n\nGenerated by yolo-new-site.\n", encoding="utf-8")

    say("initializing git...")
    subprocess.run(["git", "init"], cwd=repo_dir)
    subprocess.run(["git", "branch", "-M", "main"], cwd=repo_dir)
    subprocess.run(["git", "add", "."], cwd=repo_dir)
    subprocess.run(["git", "commit", "-m", "Initial site"], cwd=repo_dir)

    say("creating GitHub repo...")
    subprocess.run(["gh", "repo", "create", name, "--public", "--source=.", "--remote=origin", "--push"], cwd=repo_dir)

    rule("DONE")
    say(f"created GitHub repo for {name}")
    say("deploy with: cd ~/{name} && vercel --prod")

if __name__ == "__main__":
    main()
