import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import { constants } from 'node:fs';

async function fileExists(path) {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch (error) {
    return false;
  }
}

test('admin portal exposes an agent operations control surface', async () => {
  const adminUrl = new URL('../admin/index.html', import.meta.url);
  assert.equal(await fileExists(adminUrl), true, 'admin/index.html should exist');

  const html = await readFile(adminUrl, 'utf8');
  assert.match(html, /Agent Operations/);
  assert.match(html, /id="agent-ops-card"/);
  assert.match(html, /id="agent-session-status"/);
  assert.match(html, /id="agent-session-alias"/);
  assert.match(html, /id="agent-session-profile"/);
  assert.match(html, /id="agent-session-reason"/);
  assert.match(html, /id="agent-host"/);
  assert.match(html, /id="agent-user"/);
  assert.match(html, /id="agent-port"/);
  assert.match(html, /id="agent-path"/);
  assert.match(html, /id="agent-service"/);
  assert.match(html, /id="agent-branch"/);
  assert.match(html, /id="agent-refresh-session"/);
  assert.match(html, /id="agent-save-config"/);
  assert.match(html, /id="agent-copy-ssh"/);
  assert.match(html, /id="agent-copy-deploy"/);
  assert.match(html, /id="agent-copy-restart"/);
  assert.match(html, /id="agent-copy-logs"/);
  assert.match(html, /id="agent-copy-heartbeat"/);
  assert.match(html, /id="agent-runtime-status"/);
  assert.match(html, /id="agent-runtime-host"/);
  assert.match(html, /id="agent-runtime-state"/);
  assert.match(html, /id="agent-runtime-beat"/);
  assert.match(html, /id="agent-runtime-inbox"/);
  assert.match(html, /id="agent-runtime-outreach"/);
  assert.match(html, /id="agent-runtime-process"/);
  assert.match(html, /Sales Loop/);
  assert.match(html, /id="agent-sales-status"/);
  assert.match(html, /id="agent-sales-generated"/);
  assert.match(html, /id="agent-sales-new"/);
  assert.match(html, /id="agent-sales-contacted"/);
  assert.match(html, /id="agent-sales-replied"/);
  assert.match(html, /id="agent-sales-failed"/);
  assert.match(html, /id="agent-sales-today"/);
  assert.match(html, /id="agent-sales-manual"/);
  assert.match(html, /id="agent-sales-recent"/);
  assert.match(html, /id="agent-sales-failures"/);
  assert.match(html, /data-agent-action="runSalesLoop"/);
  assert.match(html, /data-agent-action="checkInbox"/);
  assert.match(html, /data-agent-action="publishSales"/);
  assert.match(html, /Server Workbench/);
  assert.match(html, /data-agent-action="status"/);
  assert.match(html, /data-agent-action="pullPortal"/);
  assert.match(html, /data-agent-action="restartAgent"/);
  assert.match(html, /id="agent-terminal-input"/);
  assert.match(html, /id="agent-terminal-risk"/);
  assert.match(html, /id="agent-terminal-dir"/);
  assert.match(html, /id="agent-terminal-submit"/);
  assert.match(html, /id="agent-terminal-work"/);
  assert.match(html, /id="agent-task-input"/);
  assert.match(html, /id="agent-task-risk"/);
  assert.match(html, /id="agent-task-backend"/);
  assert.match(html, /id="agent-task-requires"/);
  assert.match(html, /id="agent-task-submit"/);
  assert.match(html, /id="agent-task-refresh"/);
  assert.match(html, /id="agent-task-status"/);
  assert.match(html, /id="agent-task-list"/);
  assert.match(html, /id="agent-runs-card"/);
  assert.match(html, /id="agent-runs-status"/);
  assert.match(html, /id="agent-runs-last"/);
  assert.match(html, /id="agent-runs-counts"/);
  assert.match(html, /id="agent-runs-routes"/);
  assert.match(html, /id="agent-runs-combo"/);
  assert.match(html, /id="agent-runs-list"/);
  assert.match(html, /portal-agent-ops-config/);
  assert.match(html, /portalRoot\.get\('agentOps'\)/);
  assert.match(html, /MANAGED_AGENT_OWNER_ALIAS = '3dvr-managed'/);
  assert.match(html, /function managedAgentQueueNode\(\)/);
  assert.match(html, /function enqueueAgentTask\(overrides = \{\}\)/);
  assert.match(html, /function enqueueTerminalCommand\(\)/);
  assert.match(html, /function enqueueWorkbenchAction\(actionKey\)/);
  assert.match(html, /function subscribeAgentSales\(\)/);
  assert.match(html, /function renderAgentSales\(sales = \{\}\)/);
  assert.match(html, /function listFromGunCollection\(value\)/);
  assert.match(html, /runtimeSalesNode\.get\('leads'\)\.on/);
  assert.match(html, /runtimeSalesNode\.get\('leads'\)\.get\('statusCounts'\)\.on/);
  assert.match(html, /runtimeSalesNode\.get\('leads'\)\.get\('routeCounts'\)\.on/);
  assert.match(html, /runtimeSalesNode\.get\('outreach'\)\.on/);
  assert.match(html, /runtimeSalesNode\.get\('inbox'\)\.on/);
  assert.match(html, /SERVER_WORKBENCH_ACTIONS/);
  assert.match(html, /backend: 'shell'/);
  assert.match(html, /requiredCapabilities: 'shell,node'/);
  assert.match(html, /3dvr sales publish/);
  assert.match(html, /3dvr sales status/);
  assert.match(html, /managedAgentQueueNode\(\)\.get\('latest'\)/);
  assert.match(html, /gun\.get\('3dvr'\)\.get\('ops'\)\.get\('autopilot'\)/);
  assert.match(html, /function ensureAgentOpsOwnerKey\(\)/);
  assert.match(html, /function persistAgentOpsConfig\(config = \{\}\)/);
  assert.match(html, /fetch\('\/api\/session'/);
  assert.match(html, /Copy deploy/);
  assert.match(html, /Copy restart/);
  assert.match(html, /Copy logs/);
  assert.match(html, /Copy heartbeat/);
  assert.match(html, /DigitalOcean host/);
  assert.match(html, /Ask 3DVR Agent/);
  assert.match(html, /Queue task/);
  assert.match(html, /Queue command/);
  assert.match(html, /Saved host details to the portal account/);
  assert.match(html, /3dvr-agent/);
  assert.match(html, /Recent Autopilot Runs/);
  assert.match(html, /Read the latest run summaries the agent already writes to Gun/);
});

test('portal home links to the agent ops dashboard', async () => {
  const portalIndex = new URL('../index.html', import.meta.url);
  assert.equal(await fileExists(portalIndex), true, 'index.html should exist');

  const html = await readFile(portalIndex, 'utf8');
  assert.match(html, /href="\/admin\/"/);
  assert.match(html, /Agent Ops/);
  assert.match(html, /portal session, control the 3dvr-agent/);
});
