import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('portal customer journey pages', () => {
  it('gives the portal home a clear concrete entry path', async () => {
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
    assert.match(html, /data-view-mode="workshop" data-active-room=""/);
    assert.match(html, /Find your purpose\. Organize your life\. Launch your world\./);
    assert.match(html, /What are you trying to organize today\?/);
    assert.match(html, /Human O\.S\./);
    assert.match(html, /data-view-mode-button="guide"/);
    assert.match(html, />Guide<\/button>/);
    assert.match(html, /Workshop/);
    assert.match(html, /Tell the portal what you need\./);
    assert.match(html, /data-auto-identity-status/);
    assert.match(html, /No login needed\. This browser remembers what helps\./);
    assert.match(html, /data-guide-form/);
    assert.match(html, /data-guide-prompt/);
    assert.match(html, /data-guide-submit/);
    assert.match(html, /data-guide-status/);
    assert.match(html, /data-guide-chip="I feel scattered and need to organize my life\."/);
    assert.match(html, /data-guide-result hidden/);
    assert.match(html, /data-guide-show-dock/);
    assert.match(html, /data-owned-app-studio hidden/);
    assert.match(html, /Only you can edit this draft\./);
    assert.match(html, /data-owned-app-builder/);
    assert.match(html, /Save draft/);
    assert.match(html, /Copy build prompt/);
    assert.match(html, /const portalGuideRoutes =/);
    assert.match(html, /id: 'app-admin'/);
    assert.match(html, /const chooseGuideRoute =/);
    assert.match(html, /const requestGuideRoute =/);
    assert.match(html, /fetch\('\/api\/openai-site'/);
    assert.match(html, /guide:\s*true/);
    assert.match(html, /AI guide is thinking/);
    assert.match(html, /Local guide ready\. AI is unavailable\./);
    assert.match(html, /const showGuideMatches =/);
    assert.match(html, /PORTAL_AUTO_IDENTITY_KEY = 'portal:auto-identity:v1'/);
    assert.match(html, /window\.PortalAutoIdentity =/);
    assert.match(html, /rememberPortalBehavior/);
    assert.match(html, /portal-auto-identity:updated/);
    assert.match(html, /lastGuideRoute/);
    assert.match(html, /OWNED_APPS_STORAGE_KEY = 'portal:owned-apps:v1'/);
    assert.match(html, /WEB_BUILDER_PREFILL_KEY = 'web-builder-prefill-request'/);
    assert.match(html, /canAdminOwnedApp/);
    assert.match(html, /handleOwnedAppIntent/);
    assert.match(html, /Only show admin controls when the active owner id matches/);
    assert.match(html, /Nine doors into the portal/);
    assert.match(html, /🧭 My Purpose/);
    assert.match(html, /🌱 My Life/);
    assert.match(html, /💡 My Ideas/);
    assert.match(html, /🛠️ My Projects/);
    assert.match(html, /💼 My Work/);
    assert.match(html, /🧠 My Learning/);
    assert.match(html, /🤝 My Community/);
    assert.match(html, /💰 My Money/);
    assert.match(html, /🕹️ 3D Play/);
    assert.match(html, /data-room-back/);
    assert.match(html, /const humanRoomTitles =/);
    assert.match(html, /document\.body\.dataset\.viewMode = mode/);
    assert.match(html, /document\.body\.dataset\.activeRoom = mode === 'human-os' \? nextRoom : ''/);
    assert.doesNotMatch(html, /Grow into your own operating system/);
    assert.match(html, /href="forge\/">Forge<\/a>/);
    assert.match(html, /href="forge\/" class="cta primary">Enter the Forge<\/a>/);
    assert.match(html, /Open CRM/);
    assert.match(html, /Open Sales/);
    assert.match(html, /Open Web Builder/);
    assert.match(html, /Featured games/);
    assert.match(html, /href="stellar-flight\.html"[\s\S]*?Game: Stellar Drift/);
    assert.match(html, /href="jetpack\.html"[\s\S]*?Game: Jetpack Corridor/);
    assert.match(html, /<span class="app-card__title">Stellar Drift<\/span>/);
    assert.match(html, /<span class="app-card__title">Jetpack Corridor<\/span>/);
    assert.ok(
      html.indexOf('Featured games') < html.indexOf('Core workspaces'),
      'expected featured games to appear before core workspaces'
    );
    assert.doesNotMatch(html, /System layers/);
    assert.doesNotMatch(html, /Cloud workspace for identity, notes, CRM, billing, messaging, and AI\./);
    assert.doesNotMatch(html, /Launcher, multi-panel workspace, media tools, and in-browser runtime experiments\./);
    assert.doesNotMatch(html, /TommyOS direction for deeper device control\./);
    assert.match(html, /Core workspaces/);
    assert.match(html, /Contacts/);
    assert.match(html, /Messenger/);
    assert.match(html, /Calendar/);
    assert.match(html, /Meetings, follow-ups, and synced schedules\./);
    assert.match(html, /Finance/);
    assert.match(html, /Billing/);
    assert.match(html, /href="start\/#paid-lanes"/);
    assert.match(html, /href="free-trial\.html"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dstarter"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dpro"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dbuilder"/);
    assert.match(html, /Get clear/);
    assert.match(html, /Family &amp; Friends/);
    assert.match(html, /Builder/);
    assert.match(html, /Start free, then grow/);
    assert.match(html, /Daily Direction/);
    assert.match(html, /Free: sort your life and choose one next step\./);
    assert.match(html, /Support Group/);
    assert.match(html, /Cell: small-group accountability and weekly momentum\./);
    assert.match(html, /Start Your Thing/);
    assert.match(html, /Start Here: organize life, ideas, work, and what wants to grow\./);
    assert.match(html, /Search the dock/);
    assert.match(html, /class="top-nav__sign-in" href="sign-in\.html\?redirect=%2Findex\.html" data-auth-entry>Sign in<\/a>/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Findex\.html" data-auth-entry>Sign in<\/a>/);
    assert.match(html, /function updatePortalAuthEntryLinks\(\)/);
    assert.match(html, /const label = signedIn \? 'Profile' : 'Sign in'/);
    assert.doesNotMatch(html, /sign-in\.html\?upgrade=guest/);
    assert.match(html, /You are already in\./);
    assert.match(html, /The portal remembers this browser\./);
    assert.doesNotMatch(html, /Sign in to save your progress/);
    assert.match(html, /class="site-backlink" href="https:\/\/3dvr\.tech\/" aria-label="Back to 3dvr\.tech home">3dvr\.tech<\/a>/);
    assert.doesNotMatch(html, />3dvr\.tech home<\/a>/);
    assert.doesNotMatch(html, /botanical-border/);
    assert.match(html, /App dock/);
    assert.match(html, /Command center/);
    assert.match(html, /Same account, same apps, deeper levels of control\./);
    assert.match(html, /<span class="app-card__title">3DVR Forge<\/span>/);
    assert.match(html, /Get clear, pick one step, and leave with a simple plan or message\./);
    assert.match(html, /<span class="app-card__title">Forge Sprint<\/span>/);
    assert.match(html, /Start \$300 sprint/);
    assert.match(html, /<span class="app-card__title">Client Onboarding Sprint<\/span>/);
    assert.match(html, /A 72-hour paid setup that turns a yes into intake, checklist, and first-week follow-up\./);
    assert.match(html, /ideas\/client-onboarding-sprint\.html/);
    assert.match(html, /data-active-room=""/);
    assert.match(html, /data-view-mode-button="guide"/);
    assert.match(html, /data-view-mode-button="workshop"/);
    assert.doesNotMatch(html, /Suggested launcher lanes/);
    assert.doesNotMatch(html, /Run the business workspace/);
    assert.doesNotMatch(html, /Open the workspace runtime/);
    assert.doesNotMatch(html, /Move toward device control/);
    assert.match(html, /data-app-list/);
    assert.match(html, /shortcut-grid/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/free-plan\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/family-friends\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/founder-plan\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/builder-plan\.html/);
  });

  it('keeps the portal homepage calm on very narrow mobile screens', async () => {
    const css = await readFile(new URL('../index-style.css', import.meta.url), 'utf8');
    const globalCss = await readFile(new URL('../styles/global.css', import.meta.url), 'utf8');

    assert.match(globalCss, /-webkit-text-size-adjust:\s*100%/);
    assert.match(globalCss, /text-size-adjust:\s*100%/);
    assert.match(css, /@media \(max-width: 380px\)/);
    assert.match(css, /\.hero-actions \.cta\s*\{/);
    assert.match(css, /body\[data-view-mode="guide"\] \.app-hub/);
    assert.match(css, /\.portal-guide\s*\{/);
    assert.match(css, /\.portal-guide__chips/);
    assert.match(css, /\.portal-guide__actions/);
    assert.match(css, /\.portal-guide__status/);
    assert.match(css, /\.portal-guide__memory/);
    assert.match(css, /\.portal-app-studio/);
    assert.match(css, /\.portal-app-studio__list button\[data-active="true"\]/);
    assert.match(css, /@media \(min-width: 721px\) \{[\s\S]*?\.hero-actions \{[\s\S]*?grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(9rem,\s*1fr\)\);[\s\S]*?\.hero-actions \.cta \{[\s\S]*?padding:\s*0\.58rem 1rem;/);
    assert.match(css, /font-size:\s*clamp\(2rem,\s*8\.8vw,\s*2\.35rem\)/);
    assert.doesNotMatch(css, /botanical-border/);
    assert.doesNotMatch(css, /body\.landing::before/);
    assert.match(css, /animation:\s*search-callout 3\.8s ease-in-out infinite/);
    assert.match(css, /\.top-nav__search::before\s*\{/);
    assert.match(css, /\.top-buttons a\.top-buttons__search-shortcut\s*\{/);
  });

  it('keeps the free trial page tied to the portal account journey', async () => {
    const html = await readFile(new URL('../free-trial.html', import.meta.url), 'utf8');
    assert.match(html, /Organize your life\. Find your next step\./);
    assert.match(html, /You are meant for more than staying stuck/);
    assert.match(html, /Open your portal/);
    assert.match(html, /Pick one move/);
    assert.match(html, /Send free link/);
    assert.match(html, /Start here/);
    assert.match(html, /Use the email you want for your portal account/);
    assert.match(html, /Sign in or create account/);
    assert.match(html, /Open billing center/);
    assert.match(html, /Open start flow/);
    assert.doesNotMatch(html, /open Life/i);
  });

  it('turns the start page into a compact onboarding router with easy plan access', async () => {
    const html = await readFile(new URL('../start/index.html', import.meta.url), 'utf8');
    assert.match(html, /Organize your life\. Find your next step\./);
    assert.match(html, /Start free if life feels scattered/);
    assert.match(html, /3 clear needs/);
    assert.match(html, /Start where you are/);
    assert.match(html, /Pick the sentence that feels true/);
    assert.match(html, /Start free/);
    assert.match(html, /Get direct help/);
    assert.match(html, /Manage billing/);
    assert.match(html, /Pick your path/);
    assert.match(html, /Three ways to begin/);
    assert.match(html, /I feel scattered/);
    assert.match(html, /I want help launching something/);
    assert.match(html, /I already pay for 3dvr/);
    assert.doesNotMatch(html, /The job of this page is simple/);
    assert.doesNotMatch(html, /Do not make every customer start on the same screen/);
    assert.match(html, /Get clear for free/);
    assert.match(html, /I need help building something/);
    assert.match(html, /Get direct help on a real project/);
    assert.match(html, /I already pay for 3DVR/);
    assert.match(html, /Manage an active subscription/);
    assert.doesNotMatch(html, /Free, paid, and existing billing each get their own first step/);
    assert.match(html, /Paid lanes/);
    assert.match(html, /Continue with \$5/);
    assert.match(html, /Continue with \$20/);
    assert.match(html, /Continue with \$50/);
    assert.match(html, /Continue with \$200/);
    assert.match(html, /Need help choosing\?/);
    assert.match(html, /What are you trying to start\?/);
    assert.match(html, /What stage is it in\?/);
    assert.match(html, /What kind of help do you want\?/);
    assert.match(html, /Just an idea/);
    assert.match(html, /Partly built/);
    assert.match(html, /Stuck and needs rescue/);
    assert.doesNotMatch(html, /What state is it in\?/);
    assert.match(html, /Best next move/);
    assert.match(html, /Open sign-in/);
    assert.match(html, /Open billing/);
    assert.match(html, /Open Daily Direction/);
    assert.match(html, /Open Projects/);
    assert.match(html, /Open Contacts/);
    assert.match(html, /Open Messenger/);
    assert.match(html, /Open Finance/);
    assert.match(html, /One portal account/);
    assert.match(html, /You are meant for more/);
    assert.match(html, /Open sign-in/);
    assert.match(html, /Browse apps/);
    assert.match(html, /Returning customers should not have to wade back through plan education\./);
    assert.match(html, /After billing, start the work cleanly/);
    assert.match(html, /mailto:3dvr\.tech@gmail\.com/);
    assert.match(html, /src="\/start\/router\.js"/);
  });
});
