import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('portal customer journey pages', () => {
  it('gives the portal home a clear concrete entry path', async () => {
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
    assert.match(html, /data-view-mode="workshop" data-active-room=""/);
    assert.match(html, /Find your purpose\. Organize your life\. Launch your world\./);
    assert.match(html, /What are you trying to organize today\?/);
    assert.match(html, /Human O\.S\./);
    assert.match(html, /Workshop/);
    assert.match(html, /Nine doors into the portal/);
    assert.match(html, /🧭 My Purpose/);
    assert.match(html, /🌱 My Life/);
    assert.match(html, /💡 My Ideas/);
    assert.match(html, /🛠️ My Projects/);
    assert.match(html, /💼 My Work/);
    assert.match(html, /🧠 My Learning/);
    assert.match(html, /🤝 My Community/);
    assert.match(html, /💰 My Money/);
    assert.match(html, /🕹️ 3D Play/);
    assert.match(html, /data-room-back/);
    assert.match(html, /const humanRoomTitles =/);
    assert.match(html, /document\.body\.dataset\.viewMode = mode/);
    assert.match(html, /document\.body\.dataset\.activeRoom = mode === 'human-os' \? nextRoom : ''/);
    assert.doesNotMatch(html, /Grow into your own operating system/);
    assert.match(html, /Open CRM/);
    assert.match(html, /Open Sales/);
    assert.match(html, /Open Web Builder/);
    assert.match(html, /Featured games/);
    assert.match(html, /href="stellar-flight\.html"[\s\S]*?Game: Stellar Drift/);
    assert.match(html, /href="jetpack\.html"[\s\S]*?Game: Jetpack Corridor/);
    assert.match(html, /<span class="app-card__title">Stellar Drift<\/span>/);
    assert.match(html, /<span class="app-card__title">Jetpack Corridor<\/span>/);
    assert.ok(
      html.indexOf('Featured games') < html.indexOf('Core workspaces'),
      'expected featured games to appear before core workspaces'
    );
    assert.doesNotMatch(html, /System layers/);
    assert.doesNotMatch(html, /Cloud workspace for identity, notes, CRM, billing, messaging, and AI\./);
    assert.doesNotMatch(html, /Launcher, multi-panel workspace, media tools, and in-browser runtime experiments\./);
    assert.doesNotMatch(html, /TommyOS direction for deeper device control\./);
    assert.match(html, /Core workspaces/);
    assert.match(html, /Contacts/);
    assert.match(html, /Messenger/);
    assert.match(html, /Calendar/);
    assert.match(html, /Meetings, follow-ups, and synced schedules\./);
    assert.match(html, /Finance/);
    assert.match(html, /Billing/);
    assert.match(html, /href="start\/#paid-lanes"/);
    assert.match(html, /href="free-trial\.html"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dstarter"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dpro"/);
    assert.match(html, /href="sign-in\.html\?redirect=%2Fbilling%2F%3Fplan%3Dbuilder"/);
    assert.match(html, /Get started/);
    assert.match(html, /Family &amp; Friends/);
    assert.match(html, /Builder/);
    assert.match(html, /Keep the support lanes nearby/);
    assert.match(html, /Daily Direction/);
    assert.match(html, /Life: 3-minute check-in and one clear next step\./);
    assert.match(html, /Support Group/);
    assert.match(html, /Cell: small-group accountability and weekly momentum\./);
    assert.match(html, /Start Your Thing/);
    assert.match(html, /Start Here: tools and paid help for a project, offer, or business\./);
    assert.match(html, /Search the dock/);
    assert.match(html, /Sign in or create account/);
    assert.match(html, /Use one account to save your progress and sync your points across devices\./);
    assert.doesNotMatch(html, /Sign in to save your progress/);
    assert.match(html, /class="site-backlink" href="https:\/\/3dvr\.tech\/" aria-label="Back to 3dvr\.tech home">3dvr\.tech<\/a>/);
    assert.doesNotMatch(html, />3dvr\.tech home<\/a>/);
    assert.doesNotMatch(html, /botanical-border/);
    assert.match(html, /App dock/);
    assert.match(html, /Command center/);
    assert.match(html, /Same account, same apps, deeper levels of control\./);
    assert.match(html, /data-active-room=""/);
    assert.match(html, /data-view-mode-button="workshop"/);
    assert.doesNotMatch(html, /Suggested launcher lanes/);
    assert.doesNotMatch(html, /Run the business workspace/);
    assert.doesNotMatch(html, /Open the workspace runtime/);
    assert.doesNotMatch(html, /Move toward device control/);
    assert.match(html, /data-app-list/);
    assert.match(html, /shortcut-grid/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/free-plan\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/family-friends\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/founder-plan\.html/);
    assert.doesNotMatch(html, /https:\/\/3dvr\.tech\/subscribe\/builder-plan\.html/);
  });

  it('keeps the portal homepage calm on very narrow mobile screens', async () => {
    const css = await readFile(new URL('../index-style.css', import.meta.url), 'utf8');
    const globalCss = await readFile(new URL('../styles/global.css', import.meta.url), 'utf8');

    assert.match(globalCss, /-webkit-text-size-adjust:\s*100%/);
    assert.match(globalCss, /text-size-adjust:\s*100%/);
    assert.match(css, /@media \(max-width: 380px\)/);
    assert.match(css, /\.hero-actions \.cta\s*\{/);
    assert.match(css, /@media \(min-width: 721px\) \{[\s\S]*?\.hero-actions \{[\s\S]*?grid-template-columns:\s*repeat\(4,\s*max-content\);[\s\S]*?\.hero-actions \.cta \{[\s\S]*?padding:\s*0\.58rem 1rem;/);
    assert.match(css, /font-size:\s*clamp\(2rem,\s*8\.8vw,\s*2\.35rem\)/);
    assert.doesNotMatch(css, /botanical-border/);
    assert.doesNotMatch(css, /body\.landing::before/);
    assert.match(css, /animation:\s*search-callout 3\.8s ease-in-out infinite/);
    assert.match(css, /\.top-nav__search::before\s*\{/);
    assert.match(css, /\.top-buttons a\.top-buttons__search-shortcut\s*\{/);
  });

  it('keeps the free trial page tied to the portal account journey', async () => {
    const html = await readFile(new URL('../free-trial.html', import.meta.url), 'utf8');
    assert.match(html, /Get organized and take your next step/);
    assert.match(html, /Create or use one portal account/);
    assert.match(html, /Start with daily direction/);
    assert.match(html, /Send free-plan link/);
    assert.match(html, /Start here/);
    assert.match(html, /Use the email you want attached to your portal account/);
    assert.match(html, /Sign in or create account/);
    assert.match(html, /Open billing center/);
    assert.match(html, /Open start flow/);
    assert.doesNotMatch(html, /open Life/i);
  });

  it('turns the start page into a compact onboarding router with easy plan access', async () => {
    const html = await readFile(new URL('../start/index.html', import.meta.url), 'utf8');
    assert.match(html, /Start your next 3dvr project\./);
    assert.match(html, /getting organized, ready for direct help, or already managing/);
    assert.match(html, /3 clear needs/);
    assert.match(html, /Start where you actually are/);
    assert.match(html, /Pick the sentence that sounds most like your situation/);
    assert.match(html, /Start free/);
    assert.match(html, /Get direct help/);
    assert.match(html, /Manage billing/);
    assert.match(html, /Pick your path/);
    assert.match(html, /Three ways to begin/);
    assert.match(html, /I am getting organized/);
    assert.match(html, /I want help launching something/);
    assert.match(html, /I already pay for 3dvr/);
    assert.doesNotMatch(html, /The job of this page is simple/);
    assert.doesNotMatch(html, /Do not make every customer start on the same screen/);
    assert.match(html, /I need to get organized/);
    assert.match(html, /Find one next step without a card/);
    assert.match(html, /I need help building something/);
    assert.match(html, /Get direct help on a real project/);
    assert.match(html, /I already pay for 3DVR/);
    assert.match(html, /Manage an active subscription/);
    assert.doesNotMatch(html, /Free, paid, and existing billing each get their own first step/);
    assert.match(html, /Paid lanes/);
    assert.match(html, /Continue with \$5/);
    assert.match(html, /Continue with \$20/);
    assert.match(html, /Continue with \$50/);
    assert.match(html, /Continue with \$200/);
    assert.match(html, /Need help choosing\?/);
    assert.match(html, /What are you trying to start\?/);
    assert.match(html, /What stage is it in\?/);
    assert.match(html, /What kind of help do you want\?/);
    assert.match(html, /Just an idea/);
    assert.match(html, /Partly built/);
    assert.match(html, /Stuck and needs rescue/);
    assert.doesNotMatch(html, /What state is it in\?/);
    assert.match(html, /Best next move/);
    assert.match(html, /Open sign-in/);
    assert.match(html, /Open billing/);
    assert.match(html, /Open Daily Direction/);
    assert.match(html, /Open Projects/);
    assert.match(html, /Open Contacts/);
    assert.match(html, /Open Messenger/);
    assert.match(html, /Open Finance/);
    assert.match(html, /One portal account/);
    assert.match(html, /Switch plans later in Stripe/);
    assert.match(html, /Open sign-in/);
    assert.match(html, /Browse apps/);
    assert.match(html, /Returning customers should not have to wade back through plan education\./);
    assert.match(html, /After billing, start the work cleanly/);
    assert.match(html, /mailto:3dvr\.tech@gmail\.com/);
    assert.match(html, /src="\/start\/router\.js"/);
  });
});
