import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('portal logo branding', () => {
  it('brands the SVG app logo and boot text as 3dvr portal', async () => {
    const logo = await readFile(new URL('../brand/portal-logo.svg', import.meta.url), 'utf8');
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
    const css = await readFile(new URL('../index-style.css', import.meta.url), 'utf8');
    const swirlScript = await readFile(new URL('../portal-swirl-logo.js', import.meta.url), 'utf8');

    assert.match(logo, /3dvr portal logo/);
    assert.match(logo, />3dvr</);
    assert.match(logo, />portal</);
    assert.match(html, /window\.__APP_NAME__ = window\.__APP_NAME__ \|\| '3dvr-portal'/);
    assert.match(html, /<strong>3dvr portal<\/strong>/);
    assert.match(html, /app-boot-enabled/);
    assert.match(html, /display-mode: standalone/);
    assert.match(html, /document\.referrer\.startsWith\('android-app:\/\/'\)/);
    assert.match(css, /\.app-boot-enabled \.app-boot/);
    assert.match(html, /portal-swirl-logo\.js/);
    assert.match(html, /data-portal-swirl-logo/);
    assert.match(html, /3dvr portal 3D swirl logo/);
    assert.match(html, /role="button"/);
    assert.match(html, /aria-pressed="false"/);
    assert.match(html, /Press to pause or resume/);
    assert.match(css, /\.portal-swirl-logo/);
    assert.match(css, /\.portal-swirl-logo\[data-logo-paused="true"\]/);
    assert.match(swirlScript, /THREE_CDN_URL/);
    assert.match(swirlScript, /three\.js\/r128\/three\.min\.js/);
    assert.match(swirlScript, /CylinderGeometry/);
    assert.match(swirlScript, /TorusGeometry/);
    assert.match(swirlScript, /CanvasTexture/);
    assert.match(swirlScript, /const BASE_FACE_SPIN = TAU \/ 5200/);
    assert.match(swirlScript, /extraFaceSpin/);
    assert.match(swirlScript, /paused: false/);
    assert.match(swirlScript, /const setPaused = \(paused\) =>/);
    assert.match(swirlScript, /root\.dataset\.logoPaused = String\(state\.paused\)/);
    assert.match(swirlScript, /root\.setAttribute\('aria-pressed', String\(state\.paused\)\)/);
    assert.match(swirlScript, /const togglePaused = \(\) =>/);
    assert.match(swirlScript, /MAX_EXTRA_SPIN = 0\.105/);
    assert.match(swirlScript, /makeTextTexture/);
    assert.match(
      swirlScript,
      /const backText = new THREE\.Mesh\(\s*textGeometry,\s*new THREE\.MeshBasicMaterial\(\{\s*map: makeTextTexture\(THREE, false\),/,
    );
    assert.doesNotMatch(swirlScript, /map: makeTextTexture\(THREE, true\)/);
    assert.match(swirlScript, /texture\.rotation = state\.faceSpin/);
    assert.match(swirlScript, /const rotationX = state\.currentX \+ state\.flipX \+ state\.wobbleX/);
    assert.match(swirlScript, /const rotationY = state\.currentY \+ state\.flipY \+ state\.wobbleY/);
    assert.match(swirlScript, /const rotationZ = state\.currentZ \+ state\.wobbleZ/);
    assert.match(swirlScript, /context\.rotate\(\(arm \/ 7\) \* TAU \+ state\.faceSpin \* 0\.7\)/);
    assert.doesNotMatch(swirlScript, /const rotationZ = state\.faceSpin/);
    assert.doesNotMatch(swirlScript, /state\.token\.rotation\.set\(rotationX, rotationY, state\.faceSpin/);
    assert.match(swirlScript, /flipVelocityX/);
    assert.match(swirlScript, /flipVelocityY/);
    assert.match(swirlScript, /MIN_FLIP_VELOCITY = 0\.005/);
    assert.match(swirlScript, /TILT_Y_LIMIT = 0\.24/);
    assert.match(swirlScript, /TILT_X_LIMIT = 0\.18/);
    assert.match(swirlScript, /FLIP_STREAK_REQUIRED = 4/);
    assert.match(swirlScript, /FLIP_STREAK_WINDOW/);
    assert.match(swirlScript, /SWIPE_STREAK_MAX = 5/);
    assert.match(swirlScript, /SWIPE_TILT_GAIN = 0\.12/);
    assert.match(swirlScript, /SWIPE_SPIN_GAIN = 0\.24/);
    assert.match(swirlScript, /TOUCH_RAMP_WINDOW = 2400/);
    assert.match(swirlScript, /TOUCH_RAMP_MAX = 6/);
    assert.match(swirlScript, /FIRST_TOUCH_SPIN_SCALE = 0\.38/);
    assert.match(swirlScript, /TOUCH_SPIN_GAIN = 0\.26/);
    assert.match(swirlScript, /FIRST_TOUCH_WOBBLE_SCALE = 0\.48/);
    assert.match(swirlScript, /TOUCH_WOBBLE_GAIN = 0\.32/);
    assert.match(swirlScript, /FIRST_TOUCH_FLIP_SCALE = 0\.74/);
    assert.match(swirlScript, /TOUCH_FLIP_GAIN = 0\.16/);
    assert.match(swirlScript, /TOUCH_INSTABILITY_IMPULSE = 0\.012/);
    assert.match(swirlScript, /TOUCH_INSTABILITY_DECAY = 0\.985/);
    assert.match(swirlScript, /FLIP_SPIN_BOOST/);
    assert.match(swirlScript, /FLIP_CROSS_IMPULSE/);
    assert.match(swirlScript, /WOBBLE_SPRING/);
    assert.match(swirlScript, /TARGET_SETTLE_BASE/);
    assert.match(swirlScript, /FLIP_HOME_EASE = 0\.075/);
    assert.match(swirlScript, /UPRIGHT_TEXT_HOME_EASE = 0\.12/);
    assert.match(swirlScript, /nearestGoodFaceAngle/);
    assert.match(swirlScript, /UPRIGHT_TEXT_STEP = TAU/);
    assert.match(swirlScript, /nearestUprightTextAngle/);
    assert.match(swirlScript, /state\.targetY = clamp\(\(point\.x - centerX\) \/ centerX, -1, 1\) \* TILT_Y_LIMIT \* tiltBoost/);
    assert.match(swirlScript, /state\.targetX = clamp\(\(point\.y - centerY\) \/ centerY, -1, 1\) \* TILT_X_LIMIT \* tiltBoost/);
    assert.match(swirlScript, /getTouchSpinScale/);
    assert.match(swirlScript, /getTouchWobbleScale/);
    assert.match(swirlScript, /getTouchFlipScale/);
    assert.match(swirlScript, /updateTouchRamp/);
    assert.match(swirlScript, /state\.extraFaceSpin - distance \* DRAG_WIND_FACTOR \* getSpinBoost\(\) \* touchSpinScale/);
    assert.match(swirlScript, /const baseSpin = state\.paused \? 0 : reducedMotion \? BASE_FACE_SPIN \* 0\.28 : BASE_FACE_SPIN/);
    assert.match(swirlScript, /const extraSpin = state\.paused \? 0 : state\.extraFaceSpin/);
    assert.match(swirlScript, /if \(wasTap\) \{\s*togglePaused\(\);/);
    assert.match(swirlScript, /if \(event\.key === ' '\) \{\s*togglePaused\(\);/);
    assert.match(swirlScript, /paused: state\.paused/);
    assert.match(swirlScript, /touchRampCount: state\.touchRampCount/);
    assert.match(swirlScript, /touchInstability: state\.touchInstability/);
    assert.match(swirlScript, /const axis = absX >= absY \? 'y' : 'x'/);
    assert.match(swirlScript, /if \(state\.flipStreakCount < FLIP_STREAK_REQUIRED\) return/);
    assert.match(swirlScript, /registerFlipGesture\('x', event\.key === 'ArrowUp' \? -1 : 1/);
    assert.match(swirlScript, /state\.flipVelocityY \+= direction \* FLIP_IMPULSE_Y \* impulseScale/);
    assert.match(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestUprightTextAngle\(state\.flipX\), UPRIGHT_TEXT_HOME_EASE\)/);
    assert.match(swirlScript, /state\.flipY = lerp\(state\.flipY, nearestGoodFaceAngle\(state\.flipY\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestGoodFaceAngle\(state\.flipX\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestUprightTextAngle\(state\.flipX\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, 0, FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipY = lerp\(state\.flipY, 0, FLIP_HOME_EASE\)/);
    assert.match(swirlScript, /state\.extraFaceSpin = clamp\(/);
    assert.match(swirlScript, /state\.wobbleVelocityY \+= dx \* DRAG_WOBBLE_FACTOR \* wobbleMultiplier/);
    assert.match(swirlScript, /state\.wobbleX = clamp\(state\.wobbleX \+ state\.wobbleVelocityX \* frames/);
    assert.match(css, /width: clamp\(7\.4rem, 19vw, 10rem\)/);
    assert.match(css, /width: clamp\(8\.4rem, 38vw, 10\.2rem\)/);
    assert.match(swirlScript, /window\.__portalSwirlLogo/);
  });
});
