import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

describe('portal logo branding', () => {
  it('brands the SVG app logo and boot text as 3dvr portal', async () => {
    const logo = await readFile(new URL('../brand/portal-logo.svg', import.meta.url), 'utf8');
    const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
    const css = await readFile(new URL('../index-style.css', import.meta.url), 'utf8');
    const swirlScript = await readFile(new URL('../portal-swirl-logo.js', import.meta.url), 'utf8');
    const heroLeadHtml = html.match(/<span class="hero-eyebrow">Human O\.S\.<\/span>[\s\S]*?<p class="hero-tagline">/)?.[0] || '';
    const swirlHtml = html.match(/<div\s+class="portal-swirl-brand">[\s\S]*?<\/div>\s*<p class="hero-tagline">/)?.[0] || '';

    assert.match(logo, /3dvr portal logo/);
    assert.match(logo, />3dvr</);
    assert.match(logo, />portal</);
    assert.match(html, /window\.__APP_NAME__ = window\.__APP_NAME__ \|\| '3dvr-portal'/);
    assert.match(html, /<strong>3dvr portal<\/strong>/);
    assert.match(html, /app-boot-enabled/);
    assert.match(html, /display-mode: standalone/);
    assert.match(html, /document\.referrer\.startsWith\('android-app:\/\/'\)/);
    assert.match(css, /\.app-boot-enabled \.app-boot/);
    assert.match(html, /portal-swirl-logo\.js/);
    assert.match(html, /data-portal-swirl-logo/);
    assert.match(heroLeadHtml, /<h1 id="landing-title">Find your purpose\. Organize your life\. Launch your world\.<\/h1>[\s\S]*?class="portal-swirl-brand"/);
    assert.match(swirlHtml, /class="portal-swirl-frame"/);
    assert.match(html, /3dvr portal 3D swirl logo/);
    assert.match(html, /role="button"/);
    assert.doesNotMatch(swirlHtml, /aria-pressed=/);
    assert.match(html, /Press and hold to pause/);
    assert.match(css, /\.portal-swirl-logo/);
    assert.match(css, /\.portal-swirl-logo\[data-logo-paused="true"\]/);
    assert.match(swirlScript, /THREE_CDN_URL/);
    assert.match(swirlScript, /three\.js\/r128\/three\.min\.js/);
    assert.match(swirlScript, /CylinderGeometry/);
    assert.match(swirlScript, /TorusGeometry/);
    assert.match(swirlScript, /CanvasTexture/);
    assert.match(swirlScript, /const BASE_FACE_SPIN = TAU \/ 5200/);
    assert.match(swirlScript, /extraFaceSpin/);
    assert.match(swirlScript, /createRadialGradient\(center, center, radius \* 0\.08, center, center, size \* 0\.66\)/);
    assert.match(swirlScript, /createRadialGradient\(0, 0, radius \* 0\.08, 0, 0, radius\)/);
    assert.doesNotMatch(swirlScript, /createRadialGradient\(size \* 0\.34, size \* 0\.24/);
    assert.doesNotMatch(swirlScript, /createRadialGradient\(-radius \* 0\.35, -radius \* 0\.42/);
    assert.match(swirlScript, /paused: false/);
    assert.match(swirlScript, /const setPaused = \(paused\) =>/);
    assert.match(swirlScript, /root\.dataset\.logoPaused = String\(state\.paused\)/);
    assert.doesNotMatch(swirlScript, /root\.setAttribute\('aria-pressed'/);
    assert.doesNotMatch(swirlScript, /const togglePaused = \(\) =>/);
    assert.match(swirlScript, /DRAG_WIND_FACTOR = 0\.00012/);
    assert.match(swirlScript, /MAX_EXTRA_SPIN = 0\.035/);
    assert.match(swirlScript, /PULL_WINDUP_FACTOR = 0\.00007/);
    assert.match(swirlScript, /MAX_PULL_WINDUP_SPIN = 0\.012/);
    assert.match(swirlScript, /SPIN_DECAY = 0\.995/);
    assert.match(swirlScript, /makeTextTexture/);
    assert.match(
      swirlScript,
      /const backText = new THREE\.Mesh\(\s*textGeometry,\s*new THREE\.MeshBasicMaterial\(\{\s*map: makeTextTexture\(THREE, false\),/,
    );
    assert.doesNotMatch(swirlScript, /map: makeTextTexture\(THREE, true\)/);
    assert.match(swirlScript, /texture\.rotation = state\.faceSpin/);
    assert.match(swirlScript, /const rotationX = state\.currentX \+ state\.flipX \+ state\.wobbleX/);
    assert.match(swirlScript, /const rotationY = state\.currentY \+ state\.flipY \+ state\.wobbleY/);
    assert.match(swirlScript, /const rotationZ = state\.currentZ \+ state\.wobbleZ/);
    assert.match(swirlScript, /context\.rotate\(\(arm \/ 7\) \* TAU \+ state\.faceSpin \* 0\.7\)/);
    assert.doesNotMatch(swirlScript, /const rotationZ = state\.faceSpin/);
    assert.doesNotMatch(swirlScript, /state\.token\.rotation\.set\(rotationX, rotationY, state\.faceSpin/);
    assert.match(swirlScript, /flipVelocityX/);
    assert.match(swirlScript, /flipVelocityY/);
    assert.match(swirlScript, /MIN_FLIP_VELOCITY = 0\.005/);
    assert.match(swirlScript, /TILT_Y_LIMIT = 0\.24/);
    assert.match(swirlScript, /TILT_X_LIMIT = 0\.18/);
    assert.match(swirlScript, /FLIP_STREAK_REQUIRED = 4/);
    assert.match(swirlScript, /FLIP_STREAK_WINDOW = 3200/);
    assert.match(swirlScript, /SWIPE_STREAK_MAX = 5/);
    assert.match(swirlScript, /SWIPE_TILT_GAIN = 0\.2/);
    assert.match(swirlScript, /SWIPE_SPIN_GAIN = 0\.12/);
    assert.match(swirlScript, /HOLD_PAUSE_DELAY_MS = 260/);
    assert.match(swirlScript, /QUICK_TAP_MAX_MS = 280/);
    assert.match(swirlScript, /QUICK_TAP_PULL_DISTANCE = 72/);
    assert.match(swirlScript, /TOUCH_RAMP_WINDOW = 2400/);
    assert.match(swirlScript, /TOUCH_RAMP_MAX = 6/);
    assert.match(swirlScript, /FIRST_TOUCH_SPIN_SCALE = 0\.38/);
    assert.match(swirlScript, /TOUCH_SPIN_GAIN = 0\.18/);
    assert.match(swirlScript, /FIRST_TOUCH_WOBBLE_SCALE = 0\.48/);
    assert.match(swirlScript, /TOUCH_WOBBLE_GAIN = 0\.32/);
    assert.match(swirlScript, /FIRST_TOUCH_FLIP_SCALE = 0\.74/);
    assert.match(swirlScript, /TOUCH_FLIP_GAIN = 0\.16/);
    assert.match(swirlScript, /TOUCH_INSTABILITY_IMPULSE = 0\.012/);
    assert.match(swirlScript, /TOUCH_INSTABILITY_DECAY = 0\.985/);
    assert.match(swirlScript, /FLIP_SPIN_BOOST = 0\.006/);
    assert.match(swirlScript, /FLIP_BUILD_SPIN_STEP = 0\.0025/);
    assert.match(swirlScript, /FLIP_BUILD_IMPULSE_STEP = 0\.024/);
    assert.match(swirlScript, /FLIP_BUILD_WOBBLE_STEP = 0\.026/);
    assert.match(swirlScript, /FLIP_CROSS_IMPULSE/);
    assert.match(swirlScript, /WOBBLE_SPRING/);
    assert.match(swirlScript, /TARGET_SETTLE_BASE = 0\.965/);
    assert.match(swirlScript, /CURRENT_SETTLE_BASE = 0\.9/);
    assert.match(swirlScript, /DRAG_WOBBLE_STREAK_GAIN = 0\.48/);
    assert.match(swirlScript, /SPARK_BURST_MAX = 18/);
    assert.match(swirlScript, /SPARK_LIFETIME_MS = 720/);
    assert.match(swirlScript, /FLIP_HOME_EASE = 0\.075/);
    assert.match(swirlScript, /UPRIGHT_TEXT_HOME_EASE = 0\.12/);
    assert.match(swirlScript, /nearestGoodFaceAngle/);
    assert.match(swirlScript, /UPRIGHT_TEXT_STEP = TAU/);
    assert.match(swirlScript, /nearestUprightTextAngle/);
    assert.match(swirlScript, /state\.targetY = clamp\(\(point\.x - centerX\) \/ centerX, -1, 1\) \* TILT_Y_LIMIT \* tiltBoost/);
    assert.match(swirlScript, /state\.targetX = clamp\(\(point\.y - centerY\) \/ centerY, -1, 1\) \* TILT_X_LIMIT \* tiltBoost/);
    assert.match(swirlScript, /getTouchSpinScale/);
    assert.match(swirlScript, /getTouchWobbleScale/);
    assert.match(swirlScript, /getTouchFlipScale/);
    assert.match(swirlScript, /updateTouchRamp/);
    assert.match(swirlScript, /state\.pullWindupSpin \+ distance \* PULL_WINDUP_FACTOR \* getSpinBoost\(\) \* touchSpinScale/);
    assert.match(swirlScript, /state\.extraFaceSpin \+ distance \* DRAG_WIND_FACTOR \* getSpinBoost\(\) \* touchSpinScale/);
    assert.match(swirlScript, /state\.extraFaceSpin \+ FLIP_SPIN_BOOST \* impulseScale/);
    assert.match(swirlScript, /state\.extraFaceSpin \+\s*Math\.hypot\(state\.dragDX, state\.dragDY\) \* 0\.00035 \* getSpinBoost\(\) \* getTouchSpinScale\(\)/);
    assert.match(swirlScript, /const baseSpin = state\.paused \? 0 : reducedMotion \? BASE_FACE_SPIN \* 0\.28 : BASE_FACE_SPIN/);
    assert.match(swirlScript, /const extraSpin = state\.paused \|\| state\.dragging \? 0 : state\.extraFaceSpin/);
    assert.match(swirlScript, /const pullWindupSpin = state\.dragging \? state\.pullWindupSpin : 0/);
    assert.match(swirlScript, /const ensureSparkLayer = \(\) => \{/);
    assert.match(swirlScript, /const spawnSparks = \(count = 6, intensity = 1\) => \{/);
    assert.match(swirlScript, /spark\.dataset\.portalSpark = 'true'/);
    assert.match(swirlScript, /root\.appendChild\(layer\)/);
    assert.match(swirlScript, /state\.holdPauseTimer = window\.setTimeout/);
    assert.match(swirlScript, /if \(state\.dragging && !state\.pointerMoved\) setPaused\(true\)/);
    assert.match(swirlScript, /clearHoldPauseTimer\(\);\s*if \(state\.paused\) setPaused\(false\);/);
    assert.doesNotMatch(swirlScript, /state\.dragging = true;\s*setPaused\(true\);/);
    assert.match(swirlScript, /const stimulateQuickTap = \(\) => \{/);
    assert.match(swirlScript, /state\.lastTapStimulatedAt = now/);
    assert.match(swirlScript, /distance: QUICK_TAP_PULL_DISTANCE/);
    assert.match(swirlScript, /QUICK_TAP_PULL_DISTANCE \* 0\.00018/);
    assert.match(swirlScript, /state\.lastPointerDownDuration = now - state\.dragStartedAt/);
    assert.match(swirlScript, /if \(state\.lastPointerDownDuration <= QUICK_TAP_MAX_MS\) \{\s*stimulateQuickTap\(\);/);
    assert.match(swirlScript, /Math\.hypot\(state\.dragDX, state\.dragDY\) \* 0\.00035/);
    assert.match(swirlScript, /spawnSparks\(5, 0\.74\)/);
    assert.match(swirlScript, /spawnSparks\(7, 0\.88\)/);
    assert.match(swirlScript, /spawnSparks\(12, 1\.15\)/);
    assert.match(swirlScript, /root\.addEventListener\('click', \(event\) => \{/);
    assert.match(swirlScript, /state\.lastPointerDownDuration > QUICK_TAP_MAX_MS/);
    assert.match(swirlScript, /now - state\.lastTapStimulatedAt < 160/);
    assert.match(swirlScript, /if \(event\.key === ' '\) \{\s*if \(!event\.repeat\) setPaused\(true\);/);
    assert.match(swirlScript, /root\.addEventListener\('keyup', \(event\) => \{\s*if \(event\.key === ' '\) \{\s*setPaused\(false\);/);
    assert.match(swirlScript, /paused: state\.paused/);
    assert.match(swirlScript, /pullWindupSpin: state\.pullWindupSpin/);
    assert.match(swirlScript, /touchRampCount: state\.touchRampCount/);
    assert.match(swirlScript, /touchInstability: state\.touchInstability/);
    assert.match(swirlScript, /const axis = absX >= absY \? 'y' : 'x'/);
    assert.doesNotMatch(swirlScript, /if \(state\.paused\) \{\s*state\.extraFaceSpin = 0;/);
    assert.match(swirlScript, /const buildLevel = Math\.min\(state\.flipStreakCount, FLIP_STREAK_REQUIRED\)/);
    assert.match(swirlScript, /state\.targetY = clamp\(state\.targetY \+ direction \* buildTilt, -TILT_Y_LIMIT, TILT_Y_LIMIT\)/);
    assert.match(swirlScript, /state\.targetX = clamp\(state\.targetX \+ direction \* buildTilt, -TILT_X_LIMIT, TILT_X_LIMIT\)/);
    assert.match(swirlScript, /state\.extraFaceSpin \+ FLIP_BUILD_SPIN_STEP \* buildLevel \* buildScale/);
    assert.match(swirlScript, /if \(state\.flipStreakCount < FLIP_STREAK_REQUIRED\) return/);
    assert.match(swirlScript, /registerFlipGesture\('x', event\.key === 'ArrowUp' \? -1 : 1/);
    assert.match(swirlScript, /state\.flipVelocityY \+= direction \* FLIP_IMPULSE_Y \* impulseScale/);
    assert.match(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestUprightTextAngle\(state\.flipX\), UPRIGHT_TEXT_HOME_EASE\)/);
    assert.match(swirlScript, /state\.flipY = lerp\(state\.flipY, nearestGoodFaceAngle\(state\.flipY\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestGoodFaceAngle\(state\.flipX\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, nearestUprightTextAngle\(state\.flipX\), FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipX = lerp\(state\.flipX, 0, FLIP_HOME_EASE\)/);
    assert.doesNotMatch(swirlScript, /state\.flipY = lerp\(state\.flipY, 0, FLIP_HOME_EASE\)/);
    assert.match(swirlScript, /state\.extraFaceSpin = clamp\(/);
    assert.match(swirlScript, /state\.wobbleVelocityY \+= dx \* DRAG_WOBBLE_FACTOR \* wobbleMultiplier/);
    assert.match(swirlScript, /state\.wobbleX = clamp\(state\.wobbleX \+ state\.wobbleVelocityX \* frames/);
    assert.match(css, /\.hero-main > h1 \{[\s\S]*?max-width: 17ch;/);
    assert.match(css, /\.portal-swirl-frame \{/);
    assert.match(css, /\.portal-swirl-frame::before,/);
    assert.match(css, /width: clamp\(7\.4rem, 19vw, 10rem\)/);
    assert.match(css, /@media \(min-width: 960px\) \{[\s\S]*?\.portal-swirl-brand \{[\s\S]*?width: fit-content;[\s\S]*?justify-self: center;/);
    assert.match(css, /@media \(min-width: 960px\) \{[\s\S]*?\.portal-swirl-logo \{[\s\S]*?width: clamp\(12rem, 18vw, 15\.5rem\)/);
    assert.match(css, /@media \(max-width: 640px\) \{[\s\S]*?\.portal-swirl-brand \{[\s\S]*?width: fit-content;[\s\S]*?justify-self: center;/);
    assert.match(css, /width: clamp\(8\.4rem, 38vw, 10\.2rem\)/);
    assert.match(swirlScript, /window\.__portalSwirlLogo/);
  });
});
