import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('profitability desk ties the roadmap to the live sales system', async () => {
  const salesHubHtml = await readFile(new URL('../sales/index.html', import.meta.url), 'utf8');
  const researchHtml = await readFile(new URL('../sales/research.html', import.meta.url), 'utf8');
  const scoreboardHtml = await readFile(new URL('../sales/scoreboard.html', import.meta.url), 'utf8');
  const scoreboardJs = await readFile(new URL('../sales/scoreboard.js', import.meta.url), 'utf8');
  const scoreboardDataJs = await readFile(new URL('../sales/scoreboard-data.js', import.meta.url), 'utf8');

  assert.match(salesHubHtml, /Profitability/);
  assert.match(salesHubHtml, /Open profitability desk/);
  assert.match(researchHtml, /Open profitability desk/);
  assert.match(researchHtml, /Run the profitability week/);

  assert.match(scoreboardHtml, /Profitability Desk/);
  assert.match(scoreboardHtml, /Weekly operator view/);
  assert.match(scoreboardHtml, /Overview/);
  assert.match(scoreboardHtml, /Subscriber\s+counts come from billing and finance sync/);
  assert.match(scoreboardHtml, /Active Stripe subscribers/);
  assert.match(scoreboardHtml, /Some paid accounts are not linked inside the portal yet\./);
  assert.match(scoreboardHtml, /Refresh Stripe totals/);
  assert.match(scoreboardHtml, /Refresh customer summaries/);
  assert.match(scoreboardHtml, /Open admin Stripe/);
  assert.match(scoreboardHtml, /Open billing recovery/);
  assert.match(scoreboardHtml, /id="liveSyncTimestamps"/);
  assert.match(scoreboardHtml, /data-live-metric="outreach"/);
  assert.match(scoreboardHtml, /data-live-metric="stripeSubscribers"/);
  assert.match(scoreboardHtml, /data-live-metric="replies"/);
  assert.match(scoreboardHtml, /data-live-metric="wins"/);
  assert.match(scoreboardHtml, /data-live-metric="queueOpen"/);
  assert.match(scoreboardHtml, /data-live-metric="deposits"/);
  assert.match(scoreboardHtml, /data-live-metric="builderCustomers"/);
  assert.match(scoreboardHtml, /data-live-metric="embeddedCustomers"/);
  assert.match(scoreboardHtml, /data-live-metric="mrr"/);
  assert.match(scoreboardHtml, /Save weekly plan/);
  assert.match(scoreboardHtml, /One product move/);
  assert.match(scoreboardHtml, /One revenue move/);
  assert.match(scoreboardHtml, /One system move/);
  assert.match(scoreboardHtml, /Linked Builder MRR \+ Linked Embedded MRR/);
  assert.match(scoreboardHtml, /type="module" src="\/sales\/scoreboard\.js"/);
  assert.match(scoreboardHtml, /\/sales\/scoreboard\.js/);
  assert.match(scoreboardHtml, /https:\/\/cdn\.jsdelivr\.net\/npm\/gun\/gun\.js/);
  assert.match(scoreboardHtml, /\/gun-init\.js/);
  assert.doesNotMatch(scoreboardHtml, /id="builderCustomers"/);
  assert.doesNotMatch(scoreboardHtml, /id="embeddedCustomers"/);

  assert.match(scoreboardJs, /from '\.\/scoreboard-data\.js'/);
  assert.match(scoreboardJs, /from '\.\.\/finance\/stripe-sync\.js'/);
  assert.match(scoreboardJs, /const GUN_QUEUE_NODE_PATH = \['3dvr-portal', 'sales-training', 'today-queue'\]/);
  assert.match(scoreboardJs, /const TOUCH_LOG_NODE_PATH = \['3dvr-portal', 'crm-touch-log'\]/);
  assert.match(scoreboardJs, /const BILLING_USAGE_TIER_NODE_PATH = \['3dvr-portal', 'billing', 'usageTier'\]/);
  assert.match(scoreboardJs, /const STRIPE_METRICS_NODE_PATH = \['3dvr-portal', 'finance', 'stripe', 'metrics', 'latest'\]/);
  assert.match(scoreboardJs, /const STRIPE_CUSTOMERS_NODE_PATH = \['3dvr-portal', 'finance', 'stripeCustomers'\]/);
  assert.match(scoreboardJs, /const SCOREBOARD_NODE_PATH = \['3dvr-portal', 'sales-scoreboard', 'weekly'\]/);
  assert.match(scoreboardJs, /reply-received/);
  assert.match(scoreboardJs, /closed-won/);
  assert.match(scoreboardJs, /summarizeLinkedBilling/);
  assert.match(scoreboardJs, /normalizeUsageTierRecord/);
  assert.match(scoreboardJs, /normalizeStripeCustomerRecord/);
  assert.match(scoreboardJs, /formatSyncTimestamp/);
  assert.match(scoreboardJs, /syncStripeCustomerSummaries/);
  assert.match(scoreboardJs, /stripeSubscribers/);
  assert.match(scoreboardJs, /async function refreshStripeTotals\(\)/);
  assert.match(scoreboardJs, /async function refreshStripeCustomers\(\)/);
  assert.match(scoreboardJs, /fetch\('\/api\/stripe\/metrics'\)/);
  assert.match(scoreboardJs, /refreshStripeTotalsButton\?\.addEventListener\('click', refreshStripeTotals\)/);
  assert.match(scoreboardJs, /refreshStripeCustomersButton\?\.addEventListener\('click', refreshStripeCustomers\)/);
  assert.match(scoreboardJs, /Shared weekly ledger saved for/);

  assert.match(scoreboardDataJs, /export function summarizeLinkedBilling/);
  assert.match(scoreboardDataJs, /export function normalizeStripeMetricsRecord/);
  assert.match(scoreboardDataJs, /export function estimateRecurringRevenue/);
});
