export const patchUiHtml = `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>3DVR Show Patchbay</title><style>
:root{color-scheme:dark}body{font-family:system-ui,sans-serif;margin:0;background:#0b0d10;color:#f3f5f7}main{max-width:900px;margin:auto;padding:24px}.top{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.card{background:#151922;border:1px solid #2b3342;border-radius:16px;padding:16px;margin:16px 0}.row{display:grid;grid-template-columns:minmax(140px,1fr) minmax(220px,2fr) auto;gap:12px;align-items:center;margin:12px 0}select,input,button{font:inherit;border-radius:10px;border:1px solid #394459;background:#0e1218;color:#fff;padding:10px}button{cursor:pointer}.status{opacity:.75;font-size:.9rem}.port{font-family:ui-monospace,monospace;font-size:.85rem;opacity:.8}@media(max-width:650px){.row{grid-template-columns:1fr}.row button{width:100%}}
</style></head><body><main><div class="top"><h1>Show Patchbay</h1><span id="node" class="status"></span></div><div class="card"><label>Control token <input id="token" type="password" autocomplete="off" placeholder="Bearer token"></label><span id="message" class="status"></span></div><div id="patches"></div><div class="card"><h2>Available ports</h2><div id="ports"></div></div></main><script>
const token=document.querySelector('#token'), patches=document.querySelector('#patches'), ports=document.querySelector('#ports'), message=document.querySelector('#message');
token.value=sessionStorage.getItem('showToken')||''; token.oninput=()=>sessionStorage.setItem('showToken',token.value);
async function load(){const [caps,manifest]=await Promise.all([fetch('/v1/capabilities').then(r=>r.json()),fetch('/v1/ports').then(r=>r.json())]);document.querySelector('#node').textContent=caps.node.name+' · '+caps.node.platform+'/'+caps.node.arch;render(manifest)}
function render(m){patches.innerHTML='';for(const logical of m.logicalOutputs){const card=document.createElement('div');card.className='card';const row=document.createElement('div');row.className='row';const label=document.createElement('strong');label.textContent=logical.label;const select=document.createElement('select');for(const p of m.ports.filter(p=>p.kind.startsWith(logical.kind.split('.')[0]))){const o=document.createElement('option');o.value=p.id;o.textContent=p.label;o.selected=m.patches[logical.id]===p.id;select.append(o)}const button=document.createElement('button');button.textContent='Patch';button.onclick=()=>setPatch(logical.id,select.value);row.append(label,select,button);card.append(row);const current=document.createElement('div');current.className='port';current.textContent='Current: '+(m.patches[logical.id]||'unpatched');card.append(current);patches.append(card)}ports.innerHTML='';for(const p of m.ports){const div=document.createElement('div');div.className='port';div.textContent=p.id+' — '+p.label+(p.default?' (default)':'');ports.append(div)}}
async function setPatch(logical,target){message.textContent='Patching…';const r=await fetch('/v1/actions',{method:'POST',headers:{authorization:'Bearer '+token.value,'content-type':'application/json'},body:JSON.stringify({type:'patch.set',payload:{logical,target}})});const b=await r.json();message.textContent=r.ok?'Patched':'Error: '+(b.error||r.status);if(r.ok)load()}
load().catch(e=>message.textContent='Error: '+e.message);
const events=new EventSource('/v1/events');events.onmessage=e=>{try{if(JSON.parse(e.data).type==='patch.changed')load()}catch{}};
</script></body></html>`;
