const ROOT = 'wenzoGallery';
const LOCAL_KEY = '3dvr-wenzo-gallery';
const state = { works: new Map() };
const els = { form: document.querySelector('#uploadForm'), file: document.querySelector('#artFile'), fileLabel: document.querySelector('#fileLabel'), title: document.querySelector('#artTitle'), note: document.querySelector('#artNote'), status: document.querySelector('#uploadStatus'), grid: document.querySelector('#galleryGrid'), count: document.querySelector('#galleryCount') };
const clean = value => String(value || '').trim();
const createId = () => `work_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
function loadLocal() { try { const saved = JSON.parse(localStorage.getItem(LOCAL_KEY) || '[]'); if (Array.isArray(saved)) saved.forEach(work => { if (work?.id && work.image) state.works.set(work.id, work); }); } catch (_) {} }
function saveLocal() { try { localStorage.setItem(LOCAL_KEY, JSON.stringify([...state.works.values()].slice(0, 30))); } catch (_) {} }
function getRoot() { if (typeof window.Gun !== 'function') { els.status.textContent = 'Gun is unavailable; this browser will keep a local copy.'; return null; } const gun = window.gun || window.Gun(window.__GUN_PEERS__ || ['https://gun-relay-3dvr.fly.dev/gun']); window.gun = gun; return gun.get('3dvr-portal').get(ROOT); }
const root = getRoot();
function formatDate(value) { const date = new Date(Number(value)); return Number.isNaN(date.getTime()) ? 'In the studio' : date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); }
function render() { const works = [...state.works.values()].filter(work => work?.image).sort((a, b) => Number(b.createdAt) - Number(a.createdAt)); els.count.textContent = `${works.length} ${works.length === 1 ? 'work' : 'works'} · shared studio`; if (!works.length) { els.grid.innerHTML = '<div class="empty-state"><span>✦</span><p>The first piece is waiting for its frame.</p></div>'; return; } els.grid.innerHTML = ''; works.slice(0, 30).forEach(work => { const card = document.createElement('article'); card.className = 'art-card'; const image = document.createElement('img'); image.src = work.image; image.alt = work.title || 'Wendy artwork'; image.loading = 'lazy'; const caption = document.createElement('div'); caption.className = 'art-card__caption'; const title = document.createElement('strong'); title.textContent = work.title || 'Untitled'; const note = document.createElement('small'); note.textContent = work.note || formatDate(work.createdAt); caption.append(title, note); card.append(image, caption); els.grid.append(card); }); }
function resizeImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error('could not read image')); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 1600 / Math.max(image.width, image.height)); const canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve(canvas.toDataURL('image/jpeg', .82)); }; image.onerror = () => reject(new Error('could not decode image')); image.src = reader.result; }; reader.readAsDataURL(file); }); }
els.file.addEventListener('change', () => { els.fileLabel.textContent = els.file.files[0]?.name || 'Choose an image'; });
els.form.addEventListener('submit', async event => { event.preventDefault(); const file = els.file.files[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) { els.status.textContent = 'That file is larger than 8 MB. Choose a smaller image.'; return; } els.form.querySelector('button').disabled = true; els.status.textContent = 'Preparing the artwork…'; try { const work = { id: createId(), title: clean(els.title.value) || 'Untitled', note: clean(els.note.value), image: await resizeImage(file), createdAt: Date.now() }; state.works.set(work.id, work); saveLocal(); render(); root?.get('works').get(work.id).put(work); els.form.reset(); els.fileLabel.textContent = 'Choose an image'; els.status.textContent = root ? 'Placed in the shared gallery.' : 'Placed in this browser’s gallery.'; } catch (error) { els.status.textContent = error.message || 'That artwork could not be added.'; } finally { els.form.querySelector('button').disabled = false; } });
function bindGun() { if (!root) return; els.status.textContent = 'Connected to the shared studio.'; root.get('works').map().on((work, id) => { if (!work?.image) return; state.works.set(work.id || id, { ...work, id: work.id || id }); saveLocal(); render(); }); }
loadLocal(); render(); bindGun();
