const ROOT = 'wenzoGallery';
const LOCAL_KEY = '3dvr-wenzo-gallery';
const state = { works: new Map() };
const els = { form: document.querySelector('#uploadForm'), file: document.querySelector('#artFile'), fileLabel: document.querySelector('#fileLabel'), preview: document.querySelector('#artPreview'), rotatePreview: document.querySelector('#rotatePreview'), title: document.querySelector('#artTitle'), note: document.querySelector('#artNote'), status: document.querySelector('#uploadStatus'), grid: document.querySelector('#galleryGrid'), count: document.querySelector('#galleryCount'), lightbox: document.querySelector('#lightbox'), lightboxImage: document.querySelector('#lightboxImage'), lightboxTitle: document.querySelector('#lightboxTitle'), lightboxClose: document.querySelector('#lightboxClose') };
let previewUrl = '';
let uploadRotation = 0;
const clean = value => String(value || '').trim();
const createId = () => `work_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
function loadLocal() { try { const saved = JSON.parse(localStorage.getItem(LOCAL_KEY) || '[]'); if (Array.isArray(saved)) saved.forEach(work => { if (work?.id && work.image) state.works.set(work.id, work); }); } catch (_) {} }
function saveLocal() { try { localStorage.setItem(LOCAL_KEY, JSON.stringify([...state.works.values()].slice(0, 30))); } catch (_) {} }
function getRoot() { if (typeof window.Gun !== 'function') { els.status.textContent = 'Gun is unavailable; this browser will keep a local copy.'; return null; } const gun = window.gun || window.Gun(window.__GUN_PEERS__ || ['https://gun-relay-3dvr.fly.dev/gun']); window.gun = gun; return gun.get('3dvr-portal').get(ROOT); }
const root = getRoot();
function formatDate(value) { const date = new Date(Number(value)); return Number.isNaN(date.getTime()) ? 'In the studio' : date.toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); }
function render() { const works = [...state.works.values()].filter(work => work?.image && !work.deleted).sort((a, b) => Number(b.createdAt) - Number(a.createdAt)); els.count.textContent = `${works.length} ${works.length === 1 ? 'work' : 'works'} · shared studio`; if (!works.length) { els.grid.innerHTML = '<div class="empty-state"><span>✦</span><p>The first piece is waiting for its frame.</p></div>'; return; } els.grid.innerHTML = ''; works.slice(0, 30).forEach(work => { const card = document.createElement('article'); card.className = 'art-card'; const image = document.createElement('img'); image.src = work.image; image.alt = work.title || 'Wendy artwork'; image.loading = 'lazy'; image.tabIndex = 0; image.setAttribute('role', 'button'); image.setAttribute('aria-label', `View ${work.title || 'artwork'} full screen`); image.addEventListener('click', () => openLightbox(work)); image.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openLightbox(work); } }); const caption = document.createElement('div'); caption.className = 'art-card__caption'; const title = document.createElement('strong'); title.textContent = work.title || 'Untitled'; const note = document.createElement('small'); note.textContent = work.note || formatDate(work.createdAt); const edit = document.createElement('button'); edit.className = 'art-card__edit'; edit.type = 'button'; edit.textContent = 'Rotate ↻'; edit.setAttribute('aria-label', `Rotate ${work.title || 'this artwork'}`); edit.addEventListener('click', () => rotateWork(work.id, edit)); const remove = document.createElement('button'); remove.className = 'art-card__delete'; remove.type = 'button'; remove.textContent = 'Delete'; remove.setAttribute('aria-label', `Delete ${work.title || 'this artwork'}`); remove.addEventListener('click', () => removeWork(work.id)); caption.append(title, note, edit, remove); card.append(image, caption); els.grid.append(card); }); }
function openLightbox(work) { els.lightboxImage.src = work.image; els.lightboxImage.alt = work.title || 'Wendy artwork'; els.lightboxTitle.textContent = work.title || 'Untitled'; els.lightbox.hidden = false; document.body.classList.add('lightbox-open'); els.lightboxClose.focus(); }
function closeLightbox() { if (els.lightbox.hidden) return; els.lightbox.hidden = true; els.lightboxImage.removeAttribute('src'); document.body.classList.remove('lightbox-open'); }
function removeWork(id) { const work = state.works.get(id); if (!work || !window.confirm(`Remove “${work.title || 'this artwork'}” from the gallery?`)) return; state.works.delete(id); saveLocal(); render(); if (root) { root.get('works').get(id).put({ id, deleted: true, deletedAt: Date.now() }); els.status.textContent = 'Removed from the shared gallery.'; } else { els.status.textContent = 'Removed from this browser’s gallery.'; } }
function resizeImage(file, rotation = 0) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onerror = () => reject(new Error('could not read image')); reader.onload = () => { const image = new Image(); image.onload = () => { const scale = Math.min(1, 1600 / Math.max(image.width, image.height)); const width = Math.max(1, Math.round(image.width * scale)); const height = Math.max(1, Math.round(image.height * scale)); const quarterTurn = Math.abs(rotation) % 2 === 1; const canvas = document.createElement('canvas'); canvas.width = quarterTurn ? height : width; canvas.height = quarterTurn ? width : height; const context = canvas.getContext('2d'); context.translate(canvas.width / 2, canvas.height / 2); context.rotate(rotation * Math.PI / 2); context.drawImage(image, -width / 2, -height / 2, width, height); resolve(canvas.toDataURL('image/jpeg', .82)); }; image.onerror = () => reject(new Error('could not decode image')); image.src = reader.result; }; reader.readAsDataURL(file); }); }
function rotateDataUrl(dataUrl) { return new Promise((resolve, reject) => { const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = image.height; canvas.height = image.width; const context = canvas.getContext('2d'); context.translate(canvas.width / 2, canvas.height / 2); context.rotate(Math.PI / 2); context.drawImage(image, -image.width / 2, -image.height / 2); resolve(canvas.toDataURL('image/jpeg', .82)); }; image.onerror = () => reject(new Error('could not rotate image')); image.src = dataUrl; }); }
function publishWork(work) { root?.get('works').get(work.id).put(work); }
function clearPreview() { if (previewUrl) URL.revokeObjectURL(previewUrl); previewUrl = ''; uploadRotation = 0; els.preview.style.transform = ''; els.preview.hidden = true; els.preview.removeAttribute('src'); els.rotatePreview.hidden = true; }
function showPreview(file) { clearPreview(); if (!file || !file.type.startsWith('image/')) return; previewUrl = URL.createObjectURL(file); els.preview.src = previewUrl; els.preview.alt = `Preview of ${file.name}`; els.preview.hidden = false; els.rotatePreview.hidden = false; }
async function rotateWork(id, button) { const work = state.works.get(id); if (!work || button.disabled) return; button.disabled = true; els.status.textContent = 'Rotating the artwork…'; try { const rotated = await rotateDataUrl(work.image); const updated = { ...work, image: rotated, updatedAt: Date.now() }; state.works.set(id, updated); saveLocal(); render(); publishWork(updated); els.status.textContent = root ? 'Artwork rotated in the shared gallery.' : 'Artwork rotated in this browser’s gallery.'; } catch (error) { els.status.textContent = error.message || 'That artwork could not be rotated.'; button.disabled = false; } }
els.file.addEventListener('change', () => { const file = els.file.files[0]; els.fileLabel.textContent = file?.name || 'Choose an image'; showPreview(file); });
els.rotatePreview.addEventListener('click', () => { uploadRotation = (uploadRotation + 1) % 4; els.preview.style.transform = `rotate(${uploadRotation * 90}deg)`; });
els.lightboxClose.addEventListener('click', closeLightbox);
els.lightbox.addEventListener('click', event => { if (event.target === els.lightbox) closeLightbox(); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeLightbox(); });
els.form.addEventListener('submit', async event => { event.preventDefault(); const file = els.file.files[0]; if (!file) return; if (file.size > 8 * 1024 * 1024) { els.status.textContent = 'That file is larger than 8 MB. Choose a smaller image.'; return; } els.form.querySelector('button[type="submit"]').disabled = true; els.status.textContent = 'Preparing the artwork…'; try { const work = { id: createId(), title: clean(els.title.value) || 'Untitled', note: clean(els.note.value), image: await resizeImage(file, uploadRotation), createdAt: Date.now() }; state.works.set(work.id, work); saveLocal(); render(); publishWork(work); els.form.reset(); els.fileLabel.textContent = 'Choose an image'; clearPreview(); els.status.textContent = root ? 'Placed in the shared gallery.' : 'Placed in this browser’s gallery.'; } catch (error) { els.status.textContent = error.message || 'That artwork could not be added.'; } finally { els.form.querySelector('button[type="submit"]').disabled = false; } });
function bindGun() { if (!root) return; els.status.textContent = 'Connected to the shared studio.'; root.get('works').map().on((work, id) => { const workId = work?.id || id; if (!workId) return; if (work?.deleted || !work?.image) { state.works.delete(workId); saveLocal(); render(); return; } state.works.set(workId, { ...work, id: workId }); saveLocal(); render(); }); }
loadLocal(); render(); bindGun();
