import { buildOutreachDraft, buildPreviewBrief, buildSearchUrls, normalizeProspect, signalSummary } from './core.js';
const STORAGE_KEY='3dvr.leadFinder.prospects.v1';const BUILDER_PREFILL_KEY='web-builder-prefill-request';const DEFAULT_PEERS=['wss://relay.3dvr.tech/gun','wss://gun-relay-3dvr.fly.dev/gun'];
const $=id=>document.getElementById(id);const state={prospects:loadProspects(),filter:'all'};const gun=typeof Gun==='function'?Gun(window.__GUN_PEERS__||DEFAULT_PEERS):null;const crmRoot=gun?.get('3dvr-crm');const operatorItemsRoot=gun?.get('3dvr-portal').get('growthOperator').get('items');
const els={searchForm:$('searchForm'),searchCategory:$('searchCategory'),searchLocation:$('searchLocation'),searchLinks:$('searchLinks'),prospectForm:$('prospectForm'),status:$('status'),list:$('prospectList'),filter:$('filter'),importInput:$('importInput'),exportButton:$('exportButton')};
function safe(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function loadProspects(){try{const value=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(value)?value.map(normalizeProspect).filter(Boolean):[]}catch{return[]}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.prospects.slice(0,250)))}function setStatus(message){els.status.textContent=message}
function put(node,data){return new Promise((resolve,reject)=>{if(!node)return reject(new Error('CRM sync is unavailable.'));const timer=setTimeout(()=>resolve({timedOut:true}),6000);node.put(data,ack=>{clearTimeout(timer);ack?.err?reject(new Error(ack.err)):resolve(ack||{})})})}
function byId(id){return state.prospects.find(item=>item.id===id)}function update(id,patch){const index=state.prospects.findIndex(item=>item.id===id);if(index<0)return null;state.prospects[index]=normalizeProspect({...state.prospects[index],...patch,updatedAt:new Date().toISOString()});persist();render();return state.prospects[index]}
function readForm(){const signals={};document.querySelectorAll('[name="signal"]').forEach(input=>signals[input.value]=input.checked);return normalizeProspect({business:$('business').value,category:$('category').value,location:$('location').value,sourceUrl:$('sourceUrl').value,website:$('website').value,email:$('email').value,phone:$('phone').value,notes:$('notes').value,signals})}
function openSearches(event){event.preventDefault();const urls=buildSearchUrls(els.searchCategory.value,els.searchLocation.value);if(!urls)return;els.searchLinks.innerHTML=`<a class="button" target="_blank" rel="noopener noreferrer" href="${safe(urls.maps)}">Google Maps</a><a class="button" target="_blank" rel="noopener noreferrer" href="${safe(urls.web)}">Google Search</a><a class="button" target="_blank" rel="noopener noreferrer" href="${safe(urls.yelp)}">Yelp</a>`;setStatus('Public searches prepared. Review results and capture only defensible opportunities.')}
function addProspect(event){event.preventDefault();const prospect=readForm();if(!prospect){setStatus('Add a business name first.');return}const existing=state.prospects.findIndex(item=>item.business.toLowerCase()===prospect.business.toLowerCase()&&item.location.toLowerCase()===prospect.location.toLowerCase());if(existing>=0)state.prospects[existing]={...prospect,id:state.prospects[existing].id,createdAt:state.prospects[existing].createdAt};else state.prospects.unshift(prospect);persist();els.prospectForm.reset();$('location').value=els.searchLocation.value||'San Diego, CA';setStatus(`${prospect.business} scored ${prospect.score}/100 · ${prospect.tier}.`);render()}
async function sendToCrm(prospect){const now=new Date().toISOString();const outreach=buildOutreachDraft(prospect);const record={id:prospect.id,name:prospect.business,company:prospect.business,email:prospect.email,phone:prospect.phone,website:prospect.website,status:'Prospect',source:'Lead Finder',tags:'source/lead-finder, intent/website, preview-prospect',primaryPain:signalSummary(prospect).join(', '),nextBestAction:'Build or review the private concept preview before outreach.',leadScore:prospect.score,notes:[prospect.notes,prospect.sourceUrl?`Public source: ${prospect.sourceUrl}`:''].filter(Boolean).join('\n\n'),created:prospect.createdAt,updated:now};const operator={id:`lead-finder-${prospect.id}`,name:prospect.business,email:prospect.email,lane:'lead',stage:'drafted',offer:'Website preview sprint',context:record.primaryPain,draft:outreach,nextStep:record.nextBestAction,source:`crm:${prospect.id}`,createdAt:prospect.createdAt,updatedAt:now};await Promise.all([put(crmRoot?.get(prospect.id),record),put(operatorItemsRoot?.get(operator.id),operator)]);update(prospect.id,{stage:'In CRM'});setStatus(`${prospect.business} is now in CRM and Growth Operator with a draft.`)}
function buildPreview(prospect){localStorage.setItem(BUILDER_PREFILL_KEY,JSON.stringify({request:buildPreviewBrief(prospect),siteTitle:`${prospect.business} concept preview`,siteGoal:'Turn mobile visitors into calls or quote requests.',audience:`Customers looking for ${prospect.category||'local services'} in ${prospect.location||'the local area'}.`}));update(prospect.id,{stage:prospect.stage==='In CRM'?'In CRM':'Preview briefed'});window.location.href='../web-builder-app/'}
async function copyDraft(prospect){await navigator.clipboard.writeText(buildOutreachDraft(prospect));setStatus(`Outreach draft copied for ${prospect.business}.`)}function removeProspect(prospect){if(!confirm(`Remove ${prospect.business} from this local finder list?`))return;state.prospects=state.prospects.filter(item=>item.id!==prospect.id);persist();render();setStatus(`${prospect.business} removed locally. CRM records were not deleted.`)}
function render(){const visible=state.prospects.filter(item=>state.filter==='all'||(state.filter==='high'&&item.score>=70)||(state.filter==='promising'&&item.score>=45&&item.score<70)||(state.filter==='crm'&&item.stage==='In CRM'));$('reviewedCount').textContent=state.prospects.length;$('qualifiedCount').textContent=state.prospects.filter(item=>item.score>=45).length;$('previewCount').textContent=state.prospects.filter(item=>item.stage==='Preview briefed'||item.previewUrl).length;$('crmCount').textContent=state.prospects.filter(item=>item.stage==='In CRM').length;if(!visible.length){els.list.innerHTML='<p class="empty">No prospects match this view.</p>';return}els.list.innerHTML=visible.map(item=>`<article class="prospect-card" data-id="${safe(item.id)}"><div class="card-top"><div><p class="eyebrow">${safe(item.tier)} · ${safe(item.stage)}</p><h2>${safe(item.business)}</h2><p>${safe([item.category,item.location].filter(Boolean).join(' · '))}</p></div><div class="score">${item.score}</div></div><div class="tags">${signalSummary(item).map(label=>`<span class="tag">${safe(label)}</span>`).join('')}</div>${item.notes?`<p>${safe(item.notes)}</p>`:''}<details><summary>Outreach draft</summary><div class="draft">${safe(buildOutreachDraft(item))}</div></details><div class="card-actions"><button class="button primary" data-action="preview">Build preview</button><button class="button" data-action="crm">Send to CRM</button><button class="button" data-action="copy">Copy outreach</button>${item.sourceUrl?`<a class="button" target="_blank" rel="noopener noreferrer" href="${safe(item.sourceUrl)}">Verify source</a>`:''}<button class="button" data-action="remove">Remove</button></div></article>`).join('')}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),prospects:state.prospects},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`3dvr-leads-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setStatus('Lead Finder backup exported.')}
async function importBackup(event){try{const payload=JSON.parse(await event.target.files[0].text());const raw=Array.isArray(payload)?payload:payload.prospects;if(!Array.isArray(raw))throw new Error('Missing prospect list');const prospects=raw.map(normalizeProspect).filter(Boolean);const merged=new Map(state.prospects.map(item=>[item.id,item]));prospects.forEach(item=>merged.set(item.id,item));state.prospects=[...merged.values()];persist();render();setStatus(`Imported ${prospects.length} prospect records.`)}catch{setStatus('That backup could not be imported.')}finally{event.target.value=''}}
els.searchForm.addEventListener('submit',openSearches);els.prospectForm.addEventListener('submit',addProspect);els.filter.addEventListener('change',()=>{state.filter=els.filter.value;render()});els.exportButton.addEventListener('click',exportBackup);els.importInput.addEventListener('change',importBackup);els.list.addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const prospect=byId(event.target.closest('[data-id]')?.dataset.id);if(!prospect)return;try{if(button.dataset.action==='preview')buildPreview(prospect);if(button.dataset.action==='crm')await sendToCrm(prospect);if(button.dataset.action==='copy')await copyDraft(prospect);if(button.dataset.action==='remove')removeProspect(prospect)}catch(error){setStatus(error.message||'That action did not complete.')}});render();
