export const SIGNAL_WEIGHTS = Object.freeze({ noWebsite:40, brokenWebsite:32, poorMobile:18, missingCta:14, missingQuoteForm:12, staleSite:8, publicEmail:6, publicPhone:4 });
export const SIGNAL_LABELS = Object.freeze({ noWebsite:'No website', brokenWebsite:'Website unavailable', poorMobile:'Weak mobile experience', missingCta:'No clear call to action', missingQuoteForm:'No quote or booking form', staleSite:'Site appears stale', publicEmail:'Public business email', publicPhone:'Public business phone' });
export function cleanText(value){return typeof value==='string'?value.trim():''}
export function slugify(value){return cleanText(value).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'prospect'}
export function normalizeUrl(value){const raw=cleanText(value);if(!raw)return'';try{const candidate=/^https?:\/\//i.test(raw)?raw:`https://${raw}`;const url=new URL(candidate);return['http:','https:'].includes(url.protocol)?url.toString():''}catch{return''}}
export function normalizeSignals(value={}){return Object.keys(SIGNAL_WEIGHTS).reduce((output,key)=>{output[key]=Boolean(value[key]);return output},{})}
export function scoreProspect(prospect={}){const signals=normalizeSignals(prospect.signals);const score=Math.min(100,Object.entries(SIGNAL_WEIGHTS).reduce((total,[key,weight])=>total+(signals[key]?weight:0),0));const tier=score>=70?'High fit':score>=45?'Promising':score>=20?'Review':'Low signal';return{score,tier,signals}}
export function normalizeProspect(value={}){const business=cleanText(value.business||value.name);if(!business)return null;const scored=scoreProspect(value);const createdAt=cleanText(value.createdAt)||new Date().toISOString();return{id:cleanText(value.id)||`lead-${slugify(business)}-${Date.now().toString(36)}`,business,category:cleanText(value.category),location:cleanText(value.location),website:normalizeUrl(value.website),sourceUrl:normalizeUrl(value.sourceUrl),email:cleanText(value.email).toLowerCase(),phone:cleanText(value.phone),notes:cleanText(value.notes),stage:cleanText(value.stage)||'Prospect',previewUrl:normalizeUrl(value.previewUrl),signals:scored.signals,score:scored.score,tier:scored.tier,createdAt,updatedAt:cleanText(value.updatedAt)||createdAt}}
export function signalSummary(prospect={}){const{signals}=scoreProspect(prospect);return Object.entries(signals).filter(([,active])=>active).map(([key])=>SIGNAL_LABELS[key])}
export function recommendedOffer(prospect={}){const signals=normalizeSignals(prospect.signals);if(signals.noWebsite||signals.brokenWebsite)return'One-page website launch';if(signals.poorMobile||signals.missingCta||signals.missingQuoteForm)return'Website conversion refresh';return'Website opportunity review'}
export function buildPreviewBrief(prospect={}){const lead=normalizeProspect(prospect);if(!lead)return'';const improvements=signalSummary(lead).filter(label=>!label.startsWith('Public business'));return[`Create a polished, mobile-first one-page website preview for ${lead.business}.`,lead.category?`Business type: ${lead.category}.`:'',lead.location?`Location: ${lead.location}.`:'',improvements.length?`Visible opportunities to solve: ${improvements.join(', ')}.`:'','Use only verified public business facts. Do not invent testimonials, licenses, prices, guarantees, or staff biographies.','Make the primary action obvious on mobile. Include services, trust signals, service area, and a contact or quote section.','Label the result as an independent 3DVR concept preview until the business approves it.'].filter(Boolean).join('\n')}
export function buildOutreachDraft(prospect={}){const lead=normalizeProspect(prospect);if(!lead)return'';const issues=signalSummary(lead).filter(label=>!label.startsWith('Public business'));const observation=issues[0]?`I noticed ${issues[0].toLowerCase()} when I looked at your public business listing.`:'I saw a straightforward opportunity to make it easier for mobile visitors to contact you.';return[`Hi ${lead.business} team — I’m Thomas with 3DVR here in San Diego.`,'',observation,`I put together a small concept for a ${recommendedOffer(lead).toLowerCase()} so you can see the idea before deciding on anything.`,'','Would you like me to send the private preview?'].join('\n')}
export function buildSearchUrls(category,location){const query=[cleanText(category),cleanText(location)].filter(Boolean).join(' ');if(!query)return null;return{maps:`https://www.google.com/maps/search/${encodeURIComponent(query)}`,web:`https://www.google.com/search?q=${encodeURIComponent(query)}`,yelp:`https://www.yelp.com/search?find_desc=${encodeURIComponent(cleanText(category))}&find_loc=${encodeURIComponent(cleanText(location))}`}}
