const test = require('node:test');
const assert = require('node:assert/strict');
const { mkdir, mkdtemp, readFile, rm, writeFile } = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');

const {
  buildAppPrompt,
  buildSitePrompt,
  runYoloApp,
  runYoloNewSite,
} = require('../thomas-agent/node/yolo-projects');

test('build prompts include the project name and prompt text', () => {
  assert.match(buildAppPrompt({ name: 'dark-horse', prompt: 'A cafe landing page' }), /Page topic: A cafe landing page/);
  assert.match(buildAppPrompt({ name: 'dark-horse', prompt: 'A cafe landing page' }), /Path: \/apps\/dark-horse/);
  assert.match(buildSitePrompt({ name: 'dark-horse', prompt: 'A cafe website' }), /Site name: dark-horse/);
  assert.match(buildSitePrompt({ name: 'dark-horse', prompt: 'A cafe website' }), /Topic: A cafe website/);
});

test('runYoloApp writes the generated page and stages it for commit', async () => {
  const repo = await mkdtemp(path.join(os.tmpdir(), '3dvr-yolo-site-'));
  const appDir = path.join(repo, 'apps', 'dark-horse');
  const target = path.join(appDir, 'index.html');
  const calls = [];
  await mkdir(appDir, { recursive: true });
  await writeFile(target, '<!DOCTYPE html><html><body>Old</body></html>\n');

  try {
    const result = await runYoloApp(['--repo', repo, 'dark-horse', 'A dark cafe landing page'], {
      skipServer: true,
      push: false,
      completion: '<!DOCTYPE html><html><body>New app</body></html>',
      runGit: (repoPath, args) => {
        calls.push({ repoPath, args });
        return { status: 0 };
      },
    });

    assert.equal(result.repoPath, repo);
    assert.equal(await readFile(target, 'utf8'), '<!DOCTYPE html><html><body>New app</body></html>\n');
    assert.deepEqual(calls.map((call) => call.args), [
      ['add', path.join('apps', 'dark-horse', 'index.html')],
      ['commit', '-m', 'Add app dark-horse'],
    ]);
  } finally {
    await rm(repo, { recursive: true, force: true });
  }
});

test('runYoloNewSite writes a new repo and calls gh repo create', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), '3dvr-yolo-root-'));
  const calls = [];

  try {
    const result = await runYoloNewSite(['--root', root, 'dark-horse', 'A coffee website'], {
      skipServer: true,
      completion: '<!DOCTYPE html><html><body>New site</body></html>',
      runGit: (repoPath, args) => {
        calls.push({ kind: 'git', repoPath, args });
        return { status: 0 };
      },
      runCommand: (command, args, options) => {
        calls.push({ kind: 'cmd', command, args, options });
        return { status: 0 };
      },
    });

    const repoDir = path.join(root, 'dark-horse');
    assert.equal(result.repoDir, repoDir);
    assert.equal(await readFile(path.join(repoDir, 'index.html'), 'utf8'), '<!DOCTYPE html><html><body>New site</body></html>\n');
    assert.equal(await readFile(path.join(repoDir, 'README.md'), 'utf8'), '# dark-horse\n\nGenerated by ask-yolo-new-site.\n');
    assert.deepEqual(calls.map((call) => call.kind), ['git', 'git', 'git', 'git', 'cmd']);
    assert.deepEqual(calls[4], {
      kind: 'cmd',
      command: 'gh',
      args: ['repo', 'create', 'dark-horse', '--public', '--source=.', '--remote=origin', '--push'],
      options: { cwd: repoDir },
    });
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
