#!/data/data/com.termux/files/usr/bin/bash
set -u
export DISPLAY=:0
export GDK_SCALE=1
export GDK_DPI_SCALE=1.00
xfce4-settings-manager &
pid=$!
"$HOME/bin/3dvr-place-class" 'settings' auto >/dev/null 2>&1 &
wait "$pid"
