const setCorsHeaders = (res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
};

function validateRequest(body) {
  const { token, projectName, html } = body || {};

  if (!token || typeof token !== 'string') {
    return 'A Vercel token is required.';
  }

  if (!projectName || typeof projectName !== 'string') {
    return 'A project name is required.';
  }

  if (!html || typeof html !== 'string') {
    return 'HTML content is required for deployment.';
  }

  const trimmed = html.trim();
  if (!trimmed || trimmed.length < 20 || !trimmed.toLowerCase().includes('<html')) {
    return 'Provide complete HTML content before deploying to Vercel.';
  }

  return null;
}

async function createDeployment({ token, projectName, html, fetchImpl = globalThis.fetch }) {
  const files = [
    { file: 'index.html', data: Buffer.from(html).toString('base64') },
    {
      file: 'README.md',
      data: Buffer.from(
        '# Generated by 3dvr OpenAI Workbench\n\n'
        + 'This site was published directly from a chat response.\n'
      ).toString('base64')
    }
  ];

  const payload = {
    name: projectName.trim().toLowerCase().replace(/[^a-z0-9-]/gi, '-'),
    files,
    projectSettings: {
      framework: null,
    },
    target: 'production',
  };

  const response = await fetchImpl('https://api.vercel.com/v13/deployments', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    const errorText = await response.text();
    const status = response.status;
    throw new Error(`Vercel error ${status}: ${errorText || 'Unknown error'}`);
  }

  const data = await response.json();
  return {
    id: data.id,
    url: data.url ? `https://${data.url}` : undefined,
    inspectUrl: data.inspectUrl,
  };
}

export function createVercelDeployHandler(options = {}) {
  const { fetchImpl = globalThis.fetch } = options;

  return async function handler(req, res) {
    setCorsHeaders(res);

    if (req.method === 'OPTIONS') {
      return res.status(200).end();
    }

    if (req.method !== 'POST') {
      return res.status(405).json({ error: 'Method Not Allowed' });
    }

    let body;
    try {
      body = req.body || {};
    } catch (err) {
      return res.status(400).json({ error: 'Invalid JSON body.' });
    }

    const validationError = validateRequest(body);
    if (validationError) {
      return res.status(400).json({ error: validationError });
    }

    try {
      const result = await createDeployment({
        token: body.token,
        projectName: body.projectName,
        html: body.html,
        fetchImpl,
      });

      return res.status(200).json({
        ...result,
        projectName: body.projectName,
        createdAt: Date.now(),
      });
    } catch (err) {
      return res.status(500).json({ error: err.message || 'Unexpected Vercel deployment error.' });
    }
  };
}

const handler = createVercelDeployHandler();
export default handler;
